export {default as Blog} from './blog/Blog.jsx'
export {default as Footer} from './footer/Footer.jsx'
export {default as features} from './features/Features.jsx'
export {default as Header} from './header/Header.jsx'
export {default as whatGPT3} from './whatGPT3/whatGPT3.jsx'